
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  8 2024 17:12:52 IST (May  8 2024 11:42:52 UTC)

// Verification Directory fv/dff 

module dff(D, clk, rst, Q, SE, scan_in, scan_out);
  input D, clk, rst, SE, scan_in;
  output Q, scan_out;
  wire D, clk, rst, SE, scan_in;
  wire Q, scan_out;
  wire n_0;
  assign scan_out = Q;
  SDFFQX1 Q_reg(.CK (clk), .D (n_0), .SI (scan_in), .SE (SE), .Q (Q));
  NOR2BX1 g4__2398(.AN (D), .B (rst), .Y (n_0));
endmodule

